def define_cards
  Card.new( "The Fool", 0, "trump", "new beginnings, possibilities, pleasure, thoughtlessness, adventure, opportunity", "indecision, hesitation, injustice, apathy, a bad choice")
  Card.new( "The Magician", 1, "trump", "creativity, self-confidence, dexterity, sleight of hand,will-power, skill", "delay, unimaginative, insecurity, lack of self-confidence")
  Card.new( "The High Priestess", 2, "trump", "knowledge, wisdom, learning, intuition, impatience, virtue, purity", "selfishness, shallowness, misunderstanding, ignorance")
  Card.new( "The Empress", 3, "trump", "development, accomplishment action, evolution", "inaction, lack on concentration, vacillation, anxiety, infidelity")
  Card.new( "The Hierophant", 5, "trump", "mercy, conformity, forgiveness, social approval, bonded, inspiration", "vulnerability, unconventionality, foolish generosity, impotence, frailty, unorthodoxy")
  Card.new( "The Lovers ", 6, "trump", "harmony, trust,romance, optimism, honor, love, harmony", "separation, frustration, unreliability,fickleness, untrustworthy")
  Card.new( "The Chariot", 7, "trump", "perseverance, rushed decision, turmoil, vengeance, adversity", "vanquishment, defeat, failure, unsuccessful")
  Card.new( "Strength", 8, "trump", "courage, conviction, strength, determination, action, heroism, virility", "pettiness, sickness, unfaithfulness, weakness")
  Card.new( "The Hermit", 9, "trump", "inner strength, prudence, withdrawal, caution, vigilance", "hastiness, rashness,immaturity, imprudence, foolishness")
  Card.new( "Wheel of Fortune", 10, "trump", "unexpected events, advancement, destiny, fortune, progress", "interruption, outside influences, failure, bad luck")
  Card.new( "Justice", 11, "trump", "equality, righteousness, virtue, honor, harmony, balance", "false accusation, unfairness, abuse, biased")
  Card.new( "The Hanged Man", 12, "trump", "change, reversal, boredom, improvement, rebirth, suspension, change", "false prophecy, useless sacrifice, unwillingness")
  Card.new( "Death", 13, "trump", "unexpected change, loss, failure, transformation, death, bad luck", "immobility, slow changes, cheating, death, stagnation")
  Card.new( "Temperance", 14, "trump", "temperance, patience, good influence, confidence, moderation", "conflict, disunion, frustration, impatience, discord ")
  Card.new( "The Devil", 15, "trump", "downfall, unexpected failure, controversy, ravage, disaster, ill tempered", "release, enlightenment, divorce, recovery")
  Card.new( "The Tower", 16, "trump", "disruption, abandonment, end of friendship, bankruptcy, downfall, unexpected events", "entrapment, imprisonment, old ways, rustic ")
  Card.new( "The Star", 17, "trump", "balance, pleasure, optimism, insight, spiritual love, hope, faith", "disappointment, bad luck, imbalance, broken dreams")
  Card.new( "The Moon", 18, "trump", "Upright, double-dealing, hidden deception, disillusionment, trickery, error, danger, disgrace", "trifling mistakes, deception discovered, negative advantage")
  Card.new( "The Sun", 19, "trump", "accomplishment, success, love, joy, happy marriage, satisfaction", "loneliness, canceled plans, unhappiness, break ups")
  Card.new( "Judgment", 20, "trump", "awakening, renewal, rejuvenation, rebirth, improvement, promotion, atonement, judgment", "disappointment, indecision, death, failure, ill-health, theft, worry")
  Card.new( "The World", 21, "trump", "perfection, recognition, success, fulfillment, eternal life", "lack of vision, disappointment, imperfection")

  Card.new( "Ace of Wands", "Ace", "wands", "profitable journey, new business, beginning, new career, birth, inheritance", "selfishness, lack of determination, setback")
  Card.new( "Two of Wands", 2, "wands", "generous person, courage, patience, courage", "impatience, domination")
  Card.new( "Three of Wands", 3, "wands", "cooperation, good partnership, success", "carelessness, arrogance, pride, mistakes")
  Card.new( "Four of Wands", 4, "wands", "dissatisfaction, kindness, reevaluation", "new relationship, new ambitions, action")
  Card.new( "Five of Wands", 5, "wands", "lawsuit or quarrel, courage, competition", "new opportunities, harmony, generosity")
  Card.new( "Six of Wands", 6, "wands", "leadership, good news, success", "postponement, bad news, pride in riches")
  Card.new( "Seven of Wands", 7, "wands", "stiff competition, victory, courage, energy", "advantage, patience, indecision")
  Card.new( "Eight of Wands", 8, "wands", "new ideas, love, journey", "violence, quarrels, courage")
  Card.new( "Nine of Wands", 9, "wands", "victory, good health, obstinacy", "weakness, ill-health, adversity")
  Card.new( "Ten of Wands", 10, "wands", "pain, ruined, failure", "cleverness, energy, strength")
  Card.new( "Page of Wands", "Page", "wands", "self-confident, charming, generous, emotional", "stable but boring, dominating, feels entitled, unrealistic about money")
  Card.new( "Knight of Wands", "Knight", "wands", "generous, journey, impetuous", "suspicion, jealousy, narrow-mindedness")
  Card.new( "Queen of Wands", "Queen", "wands", "fondness, attraction, command", "jealous, revengeful, infidelity")
  Card.new( "King of Wands", "King", "wands", "passionate, good leader, noble", "unyielding, prejudice, quarrels")

  Card.new( "Ace of Cups", "Ace", "cups", "good health, love, joy, beauty", "egotism, selfishness, hesitancy")
  Card.new( "Two of Cups", 2, "cups", "romance, friendship, cooperation", "violent passion, misunderstanding")
  Card.new( "Three of Cups", 3, "cups", "fortune, hospitality, discovery", "hidden, overindulgence, pain, gossip")
  Card.new( "Four of Cups", 4, "cups", "dissatisfaction, kindness, reevaluation, redemption", "new goals, ambitions, beginning")
  Card.new( "Five of Cups", 5, "cups", "broken marriage,vain regret, sorrow, loss ", "return, summon, hope")
  Card.new( "Six of Cups", 6, "cups", "acquaintance, good memories, acquaintance, happiness", "friendship, disappointment, past")
  Card.new( "Seven of Cups", 7, "cups", "imagination, illusion, directionless", "will-power, determination")
  Card.new( "Eight of Cups", 8, "cups", "disappointment, abandonment, misery", "pleasure, success, joy")
  Card.new( "Nine of Cups", 9, "cups", "physical well-being, hopes, security", "illness, failure, overindulgence")
  Card.new( "Ten of Cups", 10, "cups", "friendship, happiness, life", "waste, broken relationships, quarrel")
  Card.new( "Page of Cups", "Page", "cups", "sweetness, interest in literature, gentleness", "poor imagination, selfishness, no desires")
  Card.new( "Knight of Cups", "Knight", "cups", "emotional, romantic dreamer, intelligence", "idleness, untruthful, fraud, sensuality")
  Card.new( "Queen of Cups", "Queen", "cups", "loving mother, gentle, happiness", "perverse, unhappy, gloom, over-active imagination")
  Card.new( "King of Cups", "King", "cups", "kindness, willingness, enjoyment", "double-dealer, scandal, crafty, violent")

  Card.new( "Ace of Swords", "Ace", "swords", "love, valiant, victory", "obstacles, tyranny, power")
  Card.new( "Two of Swords", 2, "swords", "indecision, trouble, balanced", "unscrupulous, release")
  Card.new( "Three of Swords", 3, "swords", "broken relationship, civil war", "sorrow, loss, confusion")
  Card.new( "Four of Swords", 4, "swords", "temporary exile, strife, retreat", "social unrest, labor strikes, renewed activity")
  Card.new( "Five of Swords", 5, "swords", "defeat, cowardliness, empty victory", "unfairness, defeat, loss")
  Card.new( "Six of Swords", 6, "swords", "harmony, sorrow, journey", "obstacles, difficulties, defeat")
  Card.new( "Seven of Swords", 7, "swords", "betrayal, insolence, unwise attempt", "counsel, helpful, advice")
  Card.new( "Eight of Swords", 8, "swords", "weakness, indecision, censure", "freedom, new beginnings, relaxation")
  Card.new( "Nine of Swords", 9, "swords", "desolation, illness, suspicion, cruelty", "unselfishness, good news, healing")
  Card.new( "Ten of Swords", 10, "swords", "defeat, failure, pain", "courage, positive energy, good health")
  Card.new( "Page of Swords", "Page", "swords", "grace, diplomacy, dexterity, grace", "imposture, ill-health, cunningness")
  Card.new( "Knight of Swords", "Knight", "swords", "strong man, braver, clever person", "troublemaker, a crafty, tyranny")
  Card.new( "Queen of Swords", "Queen", "swords", "skillful, brave, clever, rush", "sly, keen, deceitful")
  Card.new( "King of Swords", "King", "swords", "powerful, friendship, counselor", "obstinate, evil intentions, judgments")

  Card.new( "Ace of Pentacles", "Ace", "pentacles", "prosperity, happiness, pleasure", "misery, greedy, money")
  Card.new( "Two of Pentacles", 2, "pentacles", "harmony, new projects, helpful", "difficulty, discouragement")
  Card.new( "Three of Pentacles", 3, "pentacles", "abilities, approval,effort, abilities", "preoccupation, ambitions")
  Card.new( "Four of Pentacles", 4, "pentacles", "ungenerous, greed, miserly", "spendthrift, obstacles, earthy possessions")
  Card.new( "Five of Pentacles", 5, "pentacles", "destitution, poor health, despair, loneliness", "employment, courage, revival")
  Card.new( "Six of Pentacles", 6, "pentacles", "prosperity, philanthropy, charity, gifts", "jealousy, miserliness, unfairness")
  Card.new( "Seven of Pentacles", 7, "pentacles", "development, re-evaluation, effort, hard work", "impatience, slow progress, investments")
  Card.new( "Eight of Pentacles", 8, "pentacles", "employment, money, learning, trade", "void, no ambition, dislike")
  Card.new( "Nine of Pentacles", 9, "pentacles", "solitude, well-being, green thumb", "caution, possible loss")
  Card.new( "Ten of Pentacles", 10, "pentacles", "wealth, property, stability", "dull, slothfulness, misfortune")
  Card.new( "Page of Pentacles", "Page", "pentacles", "kindness, new ideas/opinions, scholar", "luxury, rebellious, bad news")
  Card.new( "Knight of Pentacles", "Knight", "pentacles", "dull outlook, patience, animal lover, trustworthy", "carelessness, standstill, irresponsible")
  Card.new( "Queen of Pentacles", "Queen", "pentacles", "thoughtfulness, intelligence, talents, melancholy", "mistrust, suspicion, neglect ")
  Card.new( "King of Pentacles", "King", "pentacles", "reliable person, steadiness", "bribes, materialistic, calm")
end